params:
  #二类网服务地址 接收移动终端请求转发地址(平台提供)
  outSiteHost: http://localhost:9091/httpService/sendPostDataByJson
  #附件临时存放路径
  uploadPath: E://xiaowei//temp
  #接口访问统计
  count:
    #是否打开接口访问统计
    enable: true
    #统计文件类型 目前只支持properties
    type: properties
    #统计文件名 按日生成文件,归档当月文件夹 例如 /2020-01/accessLog1_2020-01-03.properties
    fileName: accessLog
    #统计文件存放路径
    filePath: E://xiaowei//temp//accesslog//
  #操作附件相关方法
  uploadList:
    - chatInfoUpload
    - dispatcherFeedback
    - uploadAudio
    - uploadImg
    - uploadImgBase64
    - uploadFile
    - uploadAllTypeFile
    - onDuty
    - updateReportStatus
  imageFormat:
    BMP,JPG,PNG,TIF,GIF,PCX,TGA,EXIF,FPX,SVG,PSD,CDR,PCD,DXF,UFO,EPS,AI,RAW,WMF,WEBP
  specialMap:
    queryPerson: com.finest.app.pramas.special.person.DeviceQueryResult
    queryCar: com.finest.app.pramas.special.person.DeviceQueryResult
    givePersonFaceProperty: java.lang.Object