server:
  port: 9090
  servlet:
      context-path: /
spring:
  profiles:
    active: params
  servlet:
    #文件大小 MB必须大写
    #  maxFileSize 是单个文件大小
    #  maxRequestSize是设置总上传的数据大小
    multipart:
      enabled: true
      max-file-size: 40MB
      max-request-size: 200MB
logging:
  level:
    root: info
  path: E://xiaowei//logs//trans-message//monitor